name: Fronend CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - working-directory: ./frontend
        run: |
          npm ci
          npm run lint
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - working-directory: ./frontend
        run: |
          npm ci
          npm test
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name : executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BARBERFORCE_HOST }}
          username: ${{ secrets.BARBERFORCE_USERNAME }}
          password: ${{ secrets.BARBERFORCE_PASSWORD }}
          script: |
            cd ${{ secrets.BARBERFORCE_PATH }} && git pull
            cd ${{ secrets.BARBERFORCE_FRONT_PATH }}
            npm install
            pm2 kill frontend
            npm run build
            pm2 start npm --name "frontend" -- start
