name: Fronend Lint

on:
  push:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - working-directory: ${{ secrets.BARBERFORCE_FRONT_PATH }}
        run: |
          npm ci
          npm run lint
